language: python
python:
- '2.7'
before_script:
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip -nv
- unzip -q google_appengine_1.8.8.zip
script: python tests/full.py
notifications:
  hipchat:
    rooms:
      secure: pJg9fkOYl9ljasQb1vMcYU2YtjfAKMsT2dcsYptF2pwkqhW4674HSkD/0JSXQnLdrSc95lxV/3UfFWXP1a7wp5s3Vq6S6gOv1yKoLrjV2xll+bCxK2DeGBfxutvv3ZoB4w/Up1RrcXHxqjfOdhI3im0vee/N31PFnSgDuRvIWPI=
